name: INT-release
on:
  workflow_dispatch:
  pull_request:
    branches:
      - int
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.0'
    - name: Install Compilers
      run: |
        sudo apt-get update
        sudo apt-get install --yes build-essential pkgconf libelf-dev llvm-9 clang-9 linux-tools-common linux-tools-generic
        for tool in "clang" "llc" "llvm-strip"
        do
          sudo rm -f /usr/bin/$tool
          sudo ln -s /usr/bin/$tool-9 /usr/bin/$tool
        done
      shell: bash
    - name: Build eCapture
      run: |
        make env
        make -f builder/Makefile.release snapshot SNAPSHOT_VERSION="int-pull"

    - run: | 
    
        archive_to_push="./bin/ecapture-int-linux-amd64.tar.gz"
        mv ./bin/ecapture-int-pull-linux-x86_64.tar.gz $archive_to_push
        ls -lah ./bin
